name: Generate_Readme
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "* 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
    
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64'
      - name: Install Py-Dependencies
        run: python3 -m pip install bs4 requests lxml
        
      - name: Run PyFunc-Langs
        run: python3 $GITHUB_WORKSPACE/funcs/langs.py 

      - name: Generate
        run: |
          YEARS="$((($(date +%s)-$(date +%s --date "2004-09-01"))/(3600*24*365)))"
          DAYS="$((($(date +%s)-$(date +%s --date "2004-09-01"))/(3600*24)))"
          NF_LOCAL="nevalicjus@nev"
          NF_UPTIME="$YEARS years and $(($DAYS-$YEARS*365)) days"
          NF_LANGS="$(cat $GITHUB_WORKSPACE/funcs/temp-langs.txt)"
          NF_OS="Win & WSL, Mac, Ubuntu"
          NF_SHELL="Bash"
          NF_EDITOR="Atom"
          NF_CRON="if != code; sleep"
          NF_WEBSITE="n3v.xyz"
          NF_DISCORD="Nevalicjus#2137"
          NF_TWITTER="maciejbromirski"
          NF_GITHUB="Nevalicjus"
          NF_PROJ1="InviteBot: /invitebot [invitebot.xyz]"
          NF_PROJ2="Protokolant: /protokolant"
          NF_PROJ3="MCDC: /MC-Manager"
          NF_PROJ4="DownTime: /downtime"
          echo -e "\`\`\`\n\$ nevfetch\n                   .~vVeZNgQBBBQQg9Ze1v~.\n              \`^}%B@@@@@@@@@@@@@@@@@@@@@@8%}=\`                 $NF_LOCAL\n           -Lq#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#qr-              -------------------\n        .V0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@0?.           Uptime: $NF_UPTIME\n      _l#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#l\`         Languages: $NF_LANGS\n    \`o@@@@@@@@v^r}P0@@@@@@@@@@@@@@@@@@@@ghlr<r@@@@@@@#o\`       OS: $NF_OS\n   ;0@@@@@@@@0      .?szL?*;!!!!~*|]Vox_      P@@@@@@@@0.      Shell: $NF_SHELL\n  ?@@@@@@@@@@q                                z@@@@@@@@@#?     Editor: $NF_EDITOR\n :@@@@@@@@@@@Q                                R@@@@@@@@@@@\"    Cron: $NF_CRON\n_g@@@@@@@@@@2-                                \`M@@@@@@@@@@0\na@@@@@@@@@@2                                    v@@@@@@@@@@;   contact\n#@@@@@@@@@@_                                     @@@@@@@@@@y   -------------------\n@@@@@@@@@@@.                                     @@@@@@@@@@%   Website: $NF_WEBSITE\n#@@@@@@@@@@r                                    :@@@@@@@@@@s   Discord: $NF_DISCORD\nW@@@@@@@@@@Q\`                                  _0@@@@@@@@@@*   Twitter: $NF_TWITTER\n~#@@@@@@@@@@9!                                ,Q@@@@@@@@@@#    Github: $NF_GITHUB\n ;@@@@@@@@@@@@6^.                          \`\\p@@@@@@@@@@@@~\n  n@@@@@PlVd@@@@#6Vv~_\`              \`_!?zd#@@@@@@@@@@@@#n\n   2#@@@#hr _Y#@@@@@@@#q\`          \`X#@@@@@@@@@@@@@@@@@#~\n    .d@@@@@D\` .n6#@@@#V\`             Q@@@@@@@@@@@@@@@@d.       projects\n      x0@@@@0^   \`__-                M@@@@@@@@@@@@@@0=         ------------------\n        =p#@@@#%Il]]L1,              M@@@@@@@@@@@#V=           $NF_PROJ1\n          \`vR#@@@@@@@@?              M@@@@@@@@#Pv\`             $NF_PROJ2\n              \"Lf8@@@@v              q@@@#Qa?:                 $NF_PROJ3\n                  -!v|\`              _?v!\`                     $NF_PROJ4\n\`\`\`"
          echo -e "\`\`\`\n\$ nevfetch\n                   .~vVeZNgQBBBQQg9Ze1v~.\n              \`^}%B@@@@@@@@@@@@@@@@@@@@@@8%}=\`                 $NF_LOCAL\n           -Lq#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#qr-              -------------------\n        .V0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@0?.           Uptime: $NF_UPTIME\n      _l#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#l\`         Languages: $NF_LANGS\n    \`o@@@@@@@@v^r}P0@@@@@@@@@@@@@@@@@@@@ghlr<r@@@@@@@#o\`       OS: $NF_OS\n   ;0@@@@@@@@0      .?szL?*;!!!!~*|]Vox_      P@@@@@@@@0.      Shell: $NF_SHELL\n  ?@@@@@@@@@@q                                z@@@@@@@@@#?     Editor: $NF_EDITOR\n :@@@@@@@@@@@Q                                R@@@@@@@@@@@\"    Cron: $NF_CRON\n_g@@@@@@@@@@2-                                \`M@@@@@@@@@@0\na@@@@@@@@@@2                                    v@@@@@@@@@@;   contact\n#@@@@@@@@@@_                                     @@@@@@@@@@y   -------------------\n@@@@@@@@@@@.                                     @@@@@@@@@@%   Website: $NF_WEBSITE\n#@@@@@@@@@@r                                    :@@@@@@@@@@s   Discord: $NF_DISCORD\nW@@@@@@@@@@Q\`                                  _0@@@@@@@@@@*   Twitter: $NF_TWITTER\n~#@@@@@@@@@@9!                                ,Q@@@@@@@@@@#    Github: $NF_GITHUB\n ;@@@@@@@@@@@@6^.                          \`\\p@@@@@@@@@@@@~\n  n@@@@@PlVd@@@@#6Vv~_\`              \`_!?zd#@@@@@@@@@@@@#n\n   2#@@@#hr _Y#@@@@@@@#q\`          \`X#@@@@@@@@@@@@@@@@@#~\n    .d@@@@@D\` .n6#@@@#V\`             Q@@@@@@@@@@@@@@@@d.       projects\n      x0@@@@0^   \`__-                M@@@@@@@@@@@@@@0=         ------------------\n        =p#@@@#%Il]]L1,              M@@@@@@@@@@@#V=           $NF_PROJ1\n          \`vR#@@@@@@@@?              M@@@@@@@@#Pv\`             $NF_PROJ2\n              \"Lf8@@@@v              q@@@#Qa?:                 $NF_PROJ3\n                  -!v|\`              _?v!\`                     $NF_PROJ4\n\`\`\`" > README.md

      - name: Commit & Push Changes
        run: |
          git add README.md
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git commit -am 'Readme Update' || true
          git push
